"""add accounts and transfers

Revision ID: b328d4375cde
Revises: ab9bba73af37
Create Date: 2026-08-02 11:25:01.373703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b328d4375cde'
down_revision: Union[str, Sequence[str], None] = 'ab9bba73af37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'BANK', 'SAVINGS', 'CARD', 'OTHER', name='account_type', native_enum=False, length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('initial_balance_cents', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('name', name=op.f('uq_accounts_name'))
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('counter_account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_movements_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_counter_account_id'), ['counter_account_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_movements_counter_account_id_accounts'), 'accounts', ['counter_account_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_movements_account_id_accounts'), 'accounts', ['account_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###

    # Anadidos a mano: el autogenerate de Alembic no compara CHECK constraints.
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_check_constraint(
            'transfer_requires_counter_account',
            "(type = 'TRANSFER' AND counter_account_id IS NOT NULL)"
            " OR (type <> 'TRANSFER' AND counter_account_id IS NULL)",
        )
        batch_op.create_check_constraint(
            'counter_account_differs',
            'counter_account_id IS NULL OR counter_account_id <> account_id',
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_constraint('counter_account_differs', type_='check')
        batch_op.drop_constraint(
            'transfer_requires_counter_account', type_='check',
        )

    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movements_account_id_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_movements_counter_account_id_accounts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movements_counter_account_id'))
        batch_op.drop_index(batch_op.f('ix_movements_account_id'))
        batch_op.drop_column('counter_account_id')
        batch_op.drop_column('account_id')

    op.drop_table('accounts')
    # ### end Alembic commands ###
