"""create finance and work tables

Revision ID: ab9bba73af37
Revises: 
Create Date: 2026-08-02 10:50:24.818576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab9bba73af37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at > started_at', name=op.f('ck_work_sessions_ended_after_started')),
    sa.CheckConstraint('minutes IS NULL OR minutes >= 0', name=op.f('ck_work_sessions_minutes_not_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_sessions'))
    )
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='movement_type', native_enum=False, length=20), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name=op.f('ck_movements_amount_cents_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_movements_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movements'))
    )
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movements_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_movements_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movements_type'))
        batch_op.drop_index(batch_op.f('ix_movements_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_movements_category_id'))

    op.drop_table('movements')
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_sessions_started_at'))

    op.drop_table('work_sessions')
    op.drop_table('categories')
    # ### end Alembic commands ###
